### ISSUE TITLE
Epic - Implementation of RFC `0011`: Plan to rename `Qiskit/qiskit-terra` repo to `Qiskit/qiskit`

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/RFCs#41]
**Tasks**:
- [x] preparation stage
   - [x] metapackage-repo
   - [x] rfc-discussion: https://github.com/Qiskit/RFCs/pull/31
- [x] empty-metapackage stage
   - [x] ibmq-docs-out-of-metapackage: https://github.com/Qiskit/qiskit-ibmq-provider/pull/1166
   - [x] docs-out-of-metapackage: https://github.com/Qiskit/qiskit-metapackage/issues/1722
   - [x] benchmarks-out-of-metapackage: https://github.com/Qiskit/qiskit-metapackage/issues/1723
   - [x] tutorials-out-of-metapackage: https://github.com/Qiskit/qiskit-metapackage/issues/1724
- [x] ~ibmq-out-of-metapackage stage~ because https://github.com/Qiskit/qiskit-ibmq-provider/pull/1166, this is unnecessary step 
- [x] remove-optionals : Remove the non-qiskit optionals (aka extras, such as `nature`, `finance`, etc). Leave the terra optionals in the metapackage.
   - [x] Remove optionals section from metapackage readme file https://github.com/Qiskit/qiskit-metapackage/pull/1751
   - [x] In July release, mention that optionals are going to be removed in October release https://github.com/Qiskit/qiskit-terra/pull/10206
   - [x] In October release, remove optionals from metapackage. Make the terra and metapackage optionals, the same. 
- [x] archive-metapackage stage
   - [x] move-setup-out-of-metapackage
           * https://github.com/Qiskit/qiskit-terra/pull/10610
           * https://github.com/Qiskit/qiskit-terra/pull/10611
           * https://github.com/Qiskit/qiskit-terra/pull/10530
           * https://github.com/Qiskit/qiskit-terra/pull/10443
   - [x] pre-archive: https://github.com/Qiskit/qiskit-metapackage/pull/1790
   - [x] archive-metapackage:  Done on Aug 18, 2023.
- [ ] final stage
   - [x] final-rename: Planned for Aug 21, 2023
   - [x] fix-time: two weeks after `final-rename` 
   - [ ] final-announcement

```mermaid
gantt
    dateFormat  YYYY-MM-DD
    tickInterval 1month
    axisFormat %b

    section planned releases
    %% From freeze to release
    0.24         : crit, release024, 2023-04-06, 28d   
    release 0.24 : milestone, 2023-05-04   
    %% From freeze to release
    0.25         : crit, release025, 2023-07-05, 22d
    release 0.25 : milestone, 2023-07-27    
    section preparation
    metapackage-repo :metapackage-repo, 2023-03-31, 1d
    rfc-discussion   :done, rfc-discussion, 2023-03-30, 10d
    rfc-merged   :milestone, rfc-merged, after rfc-discussion, 0d 
    section empty-metapackage
    %% These tasks are not interdepedendent and they need to be done before release025   
    ibmq-docs-out-of-metapackage    :ibmq-docs, after rfc-merged, 2w
    docs-out-of-metapackage         :docs, after ibmq-docs, 4w
    benchmarks-out-of-metapackage   :benchmarks, after docs, 4w
    tutorials-out-of-metapackage    :tutorials, after benchmarks, 4w
    section archive-metapackage
    ibmq-out-of-metapackage        :ibmq-archived, after release025, 1d
    move-setup-out-of-metapackage  :setup, after release025, 1w
    pre-archive-doc                :archive-doc, 2023-08-18, 1d
    archive-metapackage            :archive-meta, after archive-doc, 1d  
    section final
    final-rename    : finalrename, 2023-08-21, 1d
    fix-time:       : fix-time, after finalrename, 2w
    final-announcement : milestone, finalannoun
```

**Comment by jakelishman** [comment]
I don't have write permission on this repo so I can't update the checklist here, but the following Terra PRs implement most of this:
- Qiskit/qiskit-terra#10610
- Qiskit/qiskit-terra#10611
- Qiskit/qiskit-terra#10530
- Qiskit/qiskit-terra#10443

At the time of writing, I've gone through the issues on the metapackage repo and sorted them all out, transferring existing ones to the correct places or closing as appropriate, and opening a couple of new ones just so the remaining few are a complete burn-down list for archiving the metapackage.  All issues have open PRs, so once they're all merged, the metapackage repo can be archived, and Terra can be renamed `Qiskit/qiskit`.

**Comment by 1ucian0** [comment]
Almost there... we can close it once finished. I agree that there is not much actionable here beyond reactive support.

**Comment by 1ucian0** [comment]
The benchmark website is up and running and the announcement is in the making. With this, I can consider this epic closed!
