### ISSUE TITLE
Epic - Implementation of RFC 0013: Move `qiskit.algorithms` to its own package and repo

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/RFCs#48]
Tasks to implement RFC 0012: `qiskit.algorithms` migration

- [X] https://github.com/Qiskit/qiskit/pull/10406
- [X] https://github.com/Qiskit/qiskit/pull/10682
- [x] https://github.com/Qiskit/qiskit/issues/10516
- [x] Remove module from Qiskit https://github.com/Qiskit/qiskit/issues/10991

**Comment by 1ucian0** [comment]
@ElePT , you can track the task for this RFC in this issue.

**Comment by ElePT** [comment]
Finally completed!
