### ISSUE TITLE
Epic - Implementation of `RFC 0021`: Sparse observables with extended alphabets

### ISSUE THREAD

**Issue by 1ucian0** [Qiskit/RFCs#75]
Tasks to implement `RFC 0021`: Sparse observables with extended alphabets

- [x] introduce the operator and its constructor methods: https://github.com/Qiskit/qiskit/pull/12671
- [ ] add some mathematical operations on the operator
- [ ] add the methods to help consumption of the operator within the primitives
